apiVersion: v1
kind: Service
metadata:
  name: creative
  namespace: tfb-servers
spec:
  ports:
    - port: 25565
      targetPort: 25565
  selector:
    run: creative
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: creative
  namespace: tfb-servers
  labels:
    run: creative
spec:
  serviceName: "creative"
  replicas: 1
  selector:
    matchLabels:
      run: creative
  template:
    metadata:
      labels:
        run: creative
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      volumes:
      - name: git-repo-volume
        emptyDir: {}
      - name: git-secret-volume
        secret:
          secretName: git-secret
          defaultMode: 256
      - name: gradle-credentials
        secret:
          secretName: gradle-credentials
      initContainers:
      - name: delete-old-jar-files
        image: alpine
        command: ["/bin/sh", "-c"]
        args: ["rm -rf /data/*.jar && rm -rf /data/plugins/*.jar"]
        volumeMounts:
        - name: creative-pv
          mountPath: /data
      - name: git-sync
        image: k8s.gcr.io/git-sync-amd64:v2.0.6
        imagePullPolicy: Always
        volumeMounts:
        - name: git-repo-volume
          mountPath: /git-data
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/theflyingbirdsmc/TFB-Network.git"
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_ROOT
          value: "/git-data"
        - name: GIT_SYNC_DEST
          value: "temp"
        - name: GIT_SYNC_PERMISSIONS
          value: "0777"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
      - name: move-files
        image: alpine
        command: ["/bin/sh", "-c"]
        args: ["cp -r /git-data/temp/creative/* /data && rm -rf /git-data/temp"]
        volumeMounts:
        - name: git-repo-volume
          mountPath: /git-data
        - name: creative-pv
          mountPath: /data
      - name: gradle-build
        image: gradle:latest
        volumeMounts:
        - name: creative-pv
          mountPath: /data
        env:
        - name: MAVEN_URL
          value: "https://jfrog.theflyingbirds.net/artifactory"  # Set your Maven repository URL here
        - name: MAVEN_USERNAME
          valueFrom:
            secretKeyRef:
              name: gradle-credentials
              key: username
        - name: MAVEN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gradle-credentials
              key: token
        command: ["/bin/sh", "-c"]
        args: ["cd /data && gradle update -PmavenUrl=$MAVEN_URL -PmavenUsername=$MAVEN_USERNAME -PmavenPassword=$MAVEN_PASSWORD"]
      containers:
      - name: creative
        image: itzg/minecraft-server
        env:
          - name: EULA
            value: "TRUE"
          - name: TYPE
            value: "CUSTOM"
          - name: "CUSTOM_SERVER"
            value: "/data/server.jar"
          - name: ONLINE_MODE
            value: "FALSE"
          - name: SERVER_PORT
            value: "25565"
          - name: "MEMORY"
            value: "5G"
        ports:
          - containerPort: 25565
        volumeMounts:
          - name: creative-pv
            mountPath: /data
          - name: git-repo-volume
            mountPath: /git-data
        resources:
          requests:
            memory: "5Gi"
        readinessProbe:
          exec:
            command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost" ]
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          exec:
            command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost"]
          initialDelaySeconds: 120
          periodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: creative-pv
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
