enforce_secure_profile: false
listeners:
- bind_local_address: true
  force_default_server: true
  forced_hosts:
    pvp.md-5.net: pvp
  host: 0.0.0.0:25565
  max_players: 2023
  motd: ''
  ping_passthrough: false
  priorities:
  - lobby
  proxy_protocol: false
  query_enabled: false
  query_port: 25565
  tab_list: GLOBAL_PING
  tab_size: 60
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  default:
  - bungeecord.command.server
  - bungeecord.command.list
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 20000
stats: eeff8c06-80b0-49a1-ab8c-697022039a24
player_limit: 2021
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: false
disabled_commands:
- revertaddresses
servers:
  CustomSMP:
    address: customsmp
    motd: ''
    restricted: false
  creative:
    address: creative
    motd: ''
    restricted: false
  crowdcontrol:
    address: crowdcontrol
    motd: ''
    restricted: false
  factions:
    address: factions
    motd: ''
    restricted: false
  kitpvp:
    address: kitpvp
    motd: ''
    restricted: false
  lobby:
    address: lobby
    motd: ''
    restricted: false
  museum:
    address: museum
    motd: ''
    restricted: false
  parkour:
    address: parkour
    motd: ''
    restricted: false
  vanilla:
    address: vanilla
    motd: ''
    restricted: false
